
//user auth
export const REGISTER_REQUEST = "REGISTEER_REQUEST";
export const REGISTER_SUCCESS = "REGISTEER_SUCCESS";
export const REGISTER_FALIURE = "REGISTEER_FALIURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALIURE = "LOGIN_FALIURE";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_FALIURE="GET_USER_FALIURE";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";

export const LOGOUT="LOGOUT";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const SET_NEW_PASSWORD_REQUEST = "SET_NEW_PASSWORD_REQUEST";
export const SET_NEW_PASSWORD_SUCCESS = "SET_NEW_PASSWORD_SUCCESS";
export const SET_NEW_PASSWORD_FAILURE = "SET_NEW_PASSWORD_FAILURE";

